Update Calendar Component
faktenforum/faktenforum-frontend pull request #76
Opened 2024-01-08 15:11 UTC by stephanmax

2024-01-08 15:13 UTC, stephanmax commented on components/Calendar.vue
> +    <v-col>{{error.data.message}}</v-col>
I decided to put the error handling close to the component in this case, instead of adding a toast via `addNotification`. I wouldn’t expect any fetch issues with the Google calendar, and thought it would make more sense here (as long as we do not have a fail-safe calendar view.)

2024-01-08 15:14 UTC, stephanmax commented on server/api/events.get.ts
> +    const url = "https://calendar.google.com/calendar/ical/0db35a68c2032a6af654a019d419687a0b68c2b15591e637128548ec710cd2e1%40group.calendar.google.com/public/basic.ics";
Basic iCal parsing of the public calendar should be enough for now. Once we need more features/a more powerful calendar integration, we can go full-on Google API.

2024-01-08 15:36 UTC, likt0r requested changes

2024-01-12 10:26 UTC, stephanmax commented on server/api/events.get.ts
> +function parseICal(raw) {
Done. As discussed in our call, my TypeScript tooling seems to be a lot more stable now :+1: Should not miss those simple things anymore.

2024-01-12 10:27 UTC, stephanmax commented on server/api/events.get.ts
> +  catch(error) {
Done. It still stings a litte, but [this article](https://fettblog.eu/typescript-typing-catch-clauses/) convinced me that `instanceof` is the best we have atm :sweat_smile: Still seems like a lot of boilerplate to throw some errors and fallback to a generic 500, but not a priority right now and a minor topic for another day.

2024-01-12 11:23 UTC, merged